[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "1.3.2"
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
linked_list_allocator = "0.10.5"
log = "0.4.17"
riscv = "0.10.1"
